title: Rails tricks
description: Here you can find some rails tricks that I've learned
author: Rails tricks
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/ftovaro
about: Back to basic

baseurl: "https://ftovaro.github.io"
url: "https://ftovaro.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
