title: Rails tricks
description: Here you can find some rails tricks that I've learned
author: Rails tricks
logo: https://s-media-cache-ak0.pinimg.com/originals/e3/28/8b/e3288bdbdf2972ba29a5e6f86ab4755c.jpg
github: https://github.com/ftovaro
about: Back to basic

baseurl: "https://ftovaro.github.io"
url: "https://ftovaro.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
